version: '3'

services:
  db:
    image: mysql
  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_blog
    ports:
      - "8000:8000"
